{
    'name': 'School Customizations',
    'version': '12.0',
    'license': 'LGPL-3',
    'category': 'Education',
    "sequence": 3,
    'summary': 'School spesific Customization',
    'complexity': "easy",
    'author': 'Reem Elobeid',
    'website': 'http://www.markoncs.com',
    'depends': [
        'openeducat_core', 'openeducat_attendance', 'openeducat_fees', 'openeducat_admission',
    ],
    'data': [
        "data/ir.sequence.xml",
        "data/timetable_data.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizard/attendance_generate_views.xml",
        "wizard/register_invoice_views.xml",
        "views/marcon_refactor.xml",
        "views/course_refactor_views.xml",
        "views/product_views.xml",
        "views/student_views.xml",
        "views/fee_discount_views.xml",
        "views/admission_views.xml",
        "views/school_year_views.xml",
        "views/batch_views.xml",
        "views/fees_views.xml",
        "views/course_views.xml",
        "views/parent_views.xml",
        "views/regulation_views.xml",
        "views/academic_calendar_views.xml",
        "views/classroom_views.xml",
        "views/assignment_views.xml",
        "views/account_invoice_views.xml",
        "views/timetable_frame_views.xml",
        "views/template.xml",
        "views/subject_registration_views.xml",
        "views/lesson_plans_views.xml",
        "views/hr_employee_views.xml",
        "views/student_migration_views.xml",
        "views/transportation_views.xml",
        "views/subject_registration_views.xml",
        "views/lesson_plans_views.xml",
        "views/res_company_views.xml",

    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
